server.port: 8081

csv:
  lines: data/lines.csv
  delays: data/delays.csv
  stops: data/stops.csv
  times: data/times.csv

spring:
  datasource:
    url: jdbc:h2:mem:dbname;MODE=MySQL
    username: admin
    password: 123
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create